#!/usr/bin/env bash
# EduZim — bootstrap-secrets.sh
# ===================================
# Generates strong random values for the secrets that docker-compose.yml and
# every service config.py now REQUIRE (BUG-003, BUG-004 from the 2026-05-26
# audit). Writes them to .env at the repo root.
#
# Usage
# -----
#   ./scripts/bootstrap-secrets.sh           # creates .env if missing
#   ./scripts/bootstrap-secrets.sh --rotate  # rotates ALL secrets (asks first)
#   ./scripts/bootstrap-secrets.sh --check   # prints status without changing files
#
# Generated values
# ----------------
#   JWT_SECRET_KEY          openssl rand -hex 64   (128-char hex; 64 bytes of entropy)
#   INTERNAL_SERVICE_TOKEN  openssl rand -hex 32   (64-char hex; 32 bytes of entropy)
#   DB_PASSWORD             openssl rand -hex 24   (only if not already set)
#
# .env is gitignored. Never commit it.
# For production, use AWS Secrets Manager / HashiCorp Vault — never these
# generated values.

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
ENV_FILE="${REPO_ROOT}/.env"
EXAMPLE_FILE="${REPO_ROOT}/.env.example"

# Required generators
command -v openssl >/dev/null 2>&1 || {
  echo "ERROR: openssl is required. Install it and retry." >&2
  exit 1
}

ROTATE=false
CHECK=false
for arg in "$@"; do
  case "$arg" in
    --rotate) ROTATE=true ;;
    --check)  CHECK=true ;;
    -h|--help)
      sed -n '2,/^set -euo/p' "$0" | sed 's/^# \?//'
      exit 0
      ;;
    *) echo "Unknown arg: $arg" >&2; exit 2 ;;
  esac
done

# ── Check mode ──
if $CHECK; then
  if [[ -f "$ENV_FILE" ]]; then
    echo "✓ .env exists at ${ENV_FILE}"
    for key in JWT_SECRET_KEY INTERNAL_SERVICE_TOKEN DB_PASSWORD; do
      if grep -q "^${key}=" "$ENV_FILE"; then
        val="$(grep "^${key}=" "$ENV_FILE" | head -1 | cut -d= -f2-)"
        len=${#val}
        case "$val" in
          *change-me*|*change-in-production*|*dev-jwt-secret*|*DO-NOT-USE*)
            echo "  ✗ ${key}: KNOWN-BAD value (run --rotate)"
            ;;
          *)
            echo "  ✓ ${key}: present, ${len} chars"
            ;;
        esac
      else
        echo "  ✗ ${key}: MISSING (re-run without --check)"
      fi
    done
  else
    echo "✗ .env does NOT exist at ${ENV_FILE}"
    echo "  Run:  ./scripts/bootstrap-secrets.sh"
  fi
  exit 0
fi

# ── Generate / rotate ──
if [[ -f "$ENV_FILE" ]] && ! $ROTATE; then
  echo "✓ .env already exists at ${ENV_FILE}"
  echo "  To rotate ALL secrets: $0 --rotate"
  echo "  To check status:       $0 --check"
  exit 0
fi

if [[ -f "$ENV_FILE" ]] && $ROTATE; then
  echo "⚠ This will REWRITE every secret in ${ENV_FILE}."
  echo "  Running services will fail to validate existing tokens until they are restarted."
  read -p "Type ROTATE to continue: " ack
  [[ "$ack" == "ROTATE" ]] || { echo "Aborted."; exit 1; }
  backup="${ENV_FILE}.$(date +%Y%m%d-%H%M%S).bak"
  cp "$ENV_FILE" "$backup"
  echo "  Backup written to ${backup}"
fi

JWT_SECRET="$(openssl rand -hex 64)"
INTERNAL_TOKEN="$(openssl rand -hex 32)"
DB_PASSWORD="$(openssl rand -hex 24)"

cat > "$ENV_FILE" <<EOF
# EduZim local environment — generated by scripts/bootstrap-secrets.sh on $(date)
# This file is gitignored. NEVER commit it. NEVER use these values in production.
# For production secrets see docs/runbooks/secrets-rotation.md

# ── JWT (REQUIRED — BUG-003) ─────────────────────────────────────────────
JWT_SECRET_KEY=${JWT_SECRET}

# ── Internal Service Token (REQUIRED — BUG-004) ──────────────────────────
INTERNAL_SERVICE_TOKEN=${INTERNAL_TOKEN}

# ── Database ─────────────────────────────────────────────────────────────
DB_USER=eduzim
DB_PASSWORD=${DB_PASSWORD}

# ── Local-dev flags ──────────────────────────────────────────────────────
DEBUG=true
COOKIE_SECURE=false
REDIS_ENABLED=true

# ── Reference / not-secret config ────────────────────────────────────────
CORS_ORIGINS=http://localhost:3000,http://localhost:3001,http://localhost:3002
FRONTEND_URL=http://localhost:3000
EOF

chmod 600 "$ENV_FILE"

echo "✓ Wrote ${ENV_FILE} (chmod 600)"
echo ""
echo "Next:"
echo "  1. docker compose down  # if stack is up"
echo "  2. docker compose up -d"
echo ""
echo "Validation:"
echo "  $0 --check"
