/**
 * EduZim — National Mock Data
 * =============================
 * AUTO-GENERATED from scripts/data/eduzim_master.xlsx by
 * scripts/regen_mock_national.py. Do not edit by hand.
 *
 * Provides multi-province / multi-school aggregates used by the
 * sovereign (admin) dashboards. Single-school deep mock data lives
 * in ``mock-data.ts``.
 */


export interface MockProvince {
    id: string;
    code: string;
    name: string;
    region: string;
    capital: string;
}

export interface MockDistrict {
    id: string;
    code: string;
    name: string;
    province_code: string;
}

export interface MockSchoolNational {
    id: string;
    code: string;
    name: string;
    province_code: string;
    district_code: string;
    type: "PRIMARY" | "SECONDARY";
    address: string;
    phone: string;
    email: string;
    founded_year: number;
    principal_name: string;
    total_students: number;
    boys: number;
    girls: number;
    total_teachers: number;
    total_classes: number;
    student_teacher_ratio: number;
    attendance_rate: number;
    average_mark: number;
    pass_rate: number;
    billed_usd: number;
    collected_usd: number;
    outstanding_usd: number;
    collection_rate: number;
    payments_count: number;
}

export interface MockProvinceBreakdown {
    province_code: string;
    province_name: string;
    region: string;
    capital: string;
    schools_count: number;
    districts_with_schools: number;
    total_students: number;
    total_teachers: number;
    student_teacher_ratio: number;
    boys: number;
    girls: number;
    average_attendance_rate: number;
    average_pass_rate: number;
    billed_usd: number;
    collected_usd: number;
    outstanding_usd: number;
    collection_rate: number;
}

export interface MockNationalKpis {
    total_provinces: number;
    total_districts: number;
    total_schools: number;
    total_students: number;
    total_boys: number;
    total_girls: number;
    total_teachers: number;
    total_classes: number;
    average_attendance_rate: number;
    average_pass_rate: number;
    billed_usd: number;
    collected_usd: number;
    outstanding_usd: number;
    collection_rate: number;
}

export interface MockTopSchool {
    id: string;
    name: string;
    code: string;
    province_code: string;
    district_code: string;
    pass_rate: number;
    average_mark: number;
    attendance_rate: number;
    total_students: number;
}
export const MOCK_PROVINCES: MockProvince[] = [
    {
        "id": "b32b8909-1165-86a1-44f2-1a5900334fe9",
        "code": "BYO",
        "name": "Bulawayo Metropolitan",
        "region": "Matabeleland",
        "capital": "Bulawayo"
    },
    {
        "id": "793bf138-8972-5df9-df5e-39d878cc0842",
        "code": "HRE",
        "name": "Harare Metropolitan",
        "region": "Mashonaland",
        "capital": "Harare"
    },
    {
        "id": "934c1c8f-69ed-c9c8-04ef-b7c0e5c33ca6",
        "code": "MAN",
        "name": "Manicaland",
        "region": "Eastern Highlands",
        "capital": "Mutare"
    },
    {
        "id": "b96a9185-3a0b-d8df-cfd5-98864fb221ef",
        "code": "MCE",
        "name": "Mashonaland Central",
        "region": "Mashonaland",
        "capital": "Bindura"
    },
    {
        "id": "22170969-dd43-0c7d-a388-a4efaca47a9e",
        "code": "MEA",
        "name": "Mashonaland East",
        "region": "Mashonaland",
        "capital": "Marondera"
    },
    {
        "id": "06940b8d-a3b0-143e-d77d-2a88a0edfa2b",
        "code": "MWE",
        "name": "Mashonaland West",
        "region": "Mashonaland",
        "capital": "Chinhoyi"
    },
    {
        "id": "475f87b6-23b2-8b75-4f5e-0b4adba06377",
        "code": "MAS",
        "name": "Masvingo",
        "region": "Southern",
        "capital": "Masvingo"
    },
    {
        "id": "cc26fbc5-bd0b-ebd7-6268-ae72b37cfd41",
        "code": "MTN",
        "name": "Matabeleland North",
        "region": "Matabeleland",
        "capital": "Lupane"
    },
    {
        "id": "0f2ec2fb-2b2b-c408-80bb-ed71fd15a90e",
        "code": "MTS",
        "name": "Matabeleland South",
        "region": "Matabeleland",
        "capital": "Gwanda"
    },
    {
        "id": "4f6459a1-4fc9-66ca-8943-8e8e17ba2a28",
        "code": "MID",
        "name": "Midlands",
        "region": "Central",
        "capital": "Gweru"
    }
];

export const MOCK_DISTRICTS: MockDistrict[] = [
    {
        "id": "d9c8b649-7932-89cd-7d61-bac2dfd05568",
        "code": "byo-cn",
        "name": "Bulawayo Central",
        "province_code": "BYO"
    },
    {
        "id": "3ab8849f-8aeb-9d34-bfba-7fa3c624a04c",
        "code": "byo-mp",
        "name": "Mpopoma-Pelandaba",
        "province_code": "BYO"
    },
    {
        "id": "0c730000-f2a6-4fad-9daa-8f4566a9af84",
        "code": "byo-nk",
        "name": "Nkulumane",
        "province_code": "BYO"
    },
    {
        "id": "ecbc4247-bbd1-1d34-4d77-ff5f9e43e9a5",
        "code": "byo-im",
        "name": "Imbizo",
        "province_code": "BYO"
    },
    {
        "id": "e127d5be-57d2-e418-08b9-7ba5f75d6ff5",
        "code": "byo-rg",
        "name": "Reigate",
        "province_code": "BYO"
    },
    {
        "id": "b4d8bd41-d53b-9f55-278f-0327b7d1cf69",
        "code": "byo-tj",
        "name": "Tshabalala",
        "province_code": "BYO"
    },
    {
        "id": "792a6234-355a-5882-6b11-bd5564f67d15",
        "code": "hre-cn",
        "name": "Harare Central",
        "province_code": "HRE"
    },
    {
        "id": "54a10808-763e-8778-478d-fbb8358aa1de",
        "code": "hre-cb",
        "name": "Chitungwiza",
        "province_code": "HRE"
    },
    {
        "id": "2a556e8b-6e9b-83ed-3d42-95004c3fb4ab",
        "code": "hre-ep",
        "name": "Epworth",
        "province_code": "HRE"
    },
    {
        "id": "7a0cebb3-f76c-ea89-9057-e9931141873d",
        "code": "hre-mb",
        "name": "Mbare-Hatfield",
        "province_code": "HRE"
    },
    {
        "id": "94fb8e4e-90f1-8a35-323b-56f70a5f0e8e",
        "code": "hre-gw",
        "name": "Glen View-Mufakose",
        "province_code": "HRE"
    },
    {
        "id": "284bb1f0-e349-1d2c-d08e-c9a2cf2561c7",
        "code": "hre-kk",
        "name": "Kuwadzana-Warren",
        "province_code": "HRE"
    },
    {
        "id": "cdb1c03e-57d1-db00-376d-64732300a46f",
        "code": "hre-hg",
        "name": "Highfield",
        "province_code": "HRE"
    },
    {
        "id": "d1b8ba15-a3ce-045c-970b-dbe32d137e44",
        "code": "man-mtc",
        "name": "Mutare City",
        "province_code": "MAN"
    },
    {
        "id": "83a81907-0a20-3e96-88dc-71a31021a366",
        "code": "man-mtr",
        "name": "Mutare Rural",
        "province_code": "MAN"
    },
    {
        "id": "ea3d581d-c4f2-74a1-4766-65c1cbf11d9b",
        "code": "man-bua",
        "name": "Buhera",
        "province_code": "MAN"
    },
    {
        "id": "f73c1a6a-52c9-2dcf-481a-0292a163773d",
        "code": "man-chm",
        "name": "Chimanimani",
        "province_code": "MAN"
    },
    {
        "id": "f30e8175-3fd7-63e7-8841-885125de3636",
        "code": "man-chp",
        "name": "Chipinge",
        "province_code": "MAN"
    },
    {
        "id": "825e3afa-f275-224b-ba2a-5770616050d7",
        "code": "man-mks",
        "name": "Makoni",
        "province_code": "MAN"
    },
    {
        "id": "5fd0bb27-006a-630d-b93f-ca577821ed8a",
        "code": "man-mut",
        "name": "Mutasa",
        "province_code": "MAN"
    },
    {
        "id": "69f16250-9d3f-845e-b7e7-9682697014e7",
        "code": "man-nyg",
        "name": "Nyanga",
        "province_code": "MAN"
    },
    {
        "id": "b25dbaec-af08-7d15-4ecb-25c5b4546695",
        "code": "mce-bnd",
        "name": "Bindura",
        "province_code": "MCE"
    },
    {
        "id": "1287583c-73c4-6323-1b1f-caffc88b9f71",
        "code": "mce-cnt",
        "name": "Centenary",
        "province_code": "MCE"
    },
    {
        "id": "c57188b8-f5c9-5fbe-d5ec-e7c49aeab064",
        "code": "mce-gku",
        "name": "Guruve",
        "province_code": "MCE"
    },
    {
        "id": "bbfdc107-f754-a77e-ba1f-8e3c11a36182",
        "code": "mce-mke",
        "name": "Mazowe",
        "province_code": "MCE"
    },
    {
        "id": "2334fd99-40da-0de5-d4ea-d411ccba6a99",
        "code": "mce-mbi",
        "name": "Mbire",
        "province_code": "MCE"
    },
    {
        "id": "b23d74c3-20ae-092e-dd34-a4b8daa28b6b",
        "code": "mce-mtk",
        "name": "Mt Darwin",
        "province_code": "MCE"
    },
    {
        "id": "43dfecb2-4e77-9b0a-3567-ffbefaa73e5b",
        "code": "mce-rsh",
        "name": "Rushinga",
        "province_code": "MCE"
    },
    {
        "id": "72c9cac8-f4a0-36e5-846e-d249b0844a4d",
        "code": "mce-shm",
        "name": "Shamva",
        "province_code": "MCE"
    },
    {
        "id": "4185a37a-5ea4-19e7-df01-a10d09ccc678",
        "code": "mea-mrn",
        "name": "Marondera",
        "province_code": "MEA"
    },
    {
        "id": "4fc3f6b1-25bf-85e1-89e8-d8fa5974ff18",
        "code": "mea-chk",
        "name": "Chikomba",
        "province_code": "MEA"
    },
    {
        "id": "bd2abd19-b444-65a9-ea71-6eb36a65bb32",
        "code": "mea-grr",
        "name": "Goromonzi",
        "province_code": "MEA"
    },
    {
        "id": "5023acf5-5ae4-20eb-ee44-45e9fa0908fb",
        "code": "mea-htf",
        "name": "Hwedza",
        "province_code": "MEA"
    },
    {
        "id": "a5e774bb-4d7e-e828-8d04-83d2d345bdbb",
        "code": "mea-mds",
        "name": "Mudzi",
        "province_code": "MEA"
    },
    {
        "id": "5b9490d4-741b-01ec-9770-bfc14731c41d",
        "code": "mea-msh",
        "name": "Murehwa",
        "province_code": "MEA"
    },
    {
        "id": "2faabece-1228-fbd7-6a8e-9b76af4f59c8",
        "code": "mea-mtk",
        "name": "Mutoko",
        "province_code": "MEA"
    },
    {
        "id": "610c11c7-e046-7838-4133-748c7f30e615",
        "code": "mea-syp",
        "name": "Seke",
        "province_code": "MEA"
    },
    {
        "id": "ad2addb7-e9f6-8ce7-b76e-15e821540d33",
        "code": "mea-uzm",
        "name": "Uzumba-Maramba",
        "province_code": "MEA"
    },
    {
        "id": "1722bdba-a9db-95bb-d71a-beb69d9aab8b",
        "code": "mwe-chn",
        "name": "Chinhoyi",
        "province_code": "MWE"
    },
    {
        "id": "28dd54ae-5f8e-2f2f-0e39-5ad06d5caaea",
        "code": "mwe-chg",
        "name": "Chegutu",
        "province_code": "MWE"
    },
    {
        "id": "c54b4b03-a25d-1fb3-0b28-a1c14e1d699c",
        "code": "mwe-hrr",
        "name": "Hurungwe",
        "province_code": "MWE"
    },
    {
        "id": "1ee70108-2c6d-f82b-0ce4-8847a10a6e32",
        "code": "mwe-krb",
        "name": "Kariba",
        "province_code": "MWE"
    },
    {
        "id": "6ac70b8a-5c39-a381-38c6-3b6e478d3f45",
        "code": "mwe-mkd",
        "name": "Makonde",
        "province_code": "MWE"
    },
    {
        "id": "2eb38538-87a8-1c5a-df6d-e0ae00e1d5bf",
        "code": "mwe-mhd",
        "name": "Mhondoro-Ngezi",
        "province_code": "MWE"
    },
    {
        "id": "922a41ab-e61a-e0c2-8f1c-7ece4f3d5aaa",
        "code": "mwe-zvm",
        "name": "Zvimba",
        "province_code": "MWE"
    },
    {
        "id": "5cdab2d1-dce9-6e5f-9cd0-c8a7fd9738f4",
        "code": "mas-msv",
        "name": "Masvingo",
        "province_code": "MAS"
    },
    {
        "id": "ad6b3d04-75e0-8cd0-bf0e-3d6016e55b93",
        "code": "mas-bks",
        "name": "Bikita",
        "province_code": "MAS"
    },
    {
        "id": "cfe2ae44-7d8b-4692-f934-aac172343e60",
        "code": "mas-cdz",
        "name": "Chiredzi",
        "province_code": "MAS"
    },
    {
        "id": "edeafc69-1ff8-c13e-4d76-92cb90aaa513",
        "code": "mas-civ",
        "name": "Chivi",
        "province_code": "MAS"
    },
    {
        "id": "b1ad1904-08b9-a9d6-83eb-18e21ab059d6",
        "code": "mas-grj",
        "name": "Gutu",
        "province_code": "MAS"
    },
    {
        "id": "af4811a0-ac80-5bfb-f655-391b2f93f286",
        "code": "mas-mhk",
        "name": "Mwenezi",
        "province_code": "MAS"
    },
    {
        "id": "5857b1c5-c6e0-995a-5e7d-1dbc9f8f57d8",
        "code": "mas-ndg",
        "name": "Zaka",
        "province_code": "MAS"
    },
    {
        "id": "94886147-3212-9d19-2f41-52d490ac45d6",
        "code": "mtn-lpe",
        "name": "Lupane",
        "province_code": "MTN"
    },
    {
        "id": "743820b3-5956-376b-7170-44059b05e8e1",
        "code": "mtn-bbk",
        "name": "Binga",
        "province_code": "MTN"
    },
    {
        "id": "cef09276-6075-d432-aff3-58f0de763b4a",
        "code": "mtn-bbg",
        "name": "Bubi",
        "province_code": "MTN"
    },
    {
        "id": "a4db572d-3d27-c431-021a-0178e88928bf",
        "code": "mtn-hwg",
        "name": "Hwange",
        "province_code": "MTN"
    },
    {
        "id": "8ccc676c-b7d9-4c7d-abd3-09a8538282ca",
        "code": "mtn-nkb",
        "name": "Nkayi",
        "province_code": "MTN"
    },
    {
        "id": "4c92bb04-071b-2de5-9b30-97905a9fd554",
        "code": "mtn-tsh",
        "name": "Tsholotsho",
        "province_code": "MTN"
    },
    {
        "id": "304f7819-47a4-d8cc-53c8-2d7b81dd9804",
        "code": "mtn-umg",
        "name": "Umguza",
        "province_code": "MTN"
    },
    {
        "id": "2294afbb-7984-ae01-f3f7-a11530f82918",
        "code": "mts-gwd",
        "name": "Gwanda",
        "province_code": "MTS"
    },
    {
        "id": "af6f3a14-d326-e3a4-1b56-d47da8b54f03",
        "code": "mts-bei",
        "name": "Beitbridge",
        "province_code": "MTS"
    },
    {
        "id": "a66448dc-c796-43cd-c782-469572826a15",
        "code": "mts-bmb",
        "name": "Bulilima",
        "province_code": "MTS"
    },
    {
        "id": "58b3e515-c9e2-97ff-a0f2-78e186612265",
        "code": "mts-imk",
        "name": "Insiza",
        "province_code": "MTS"
    },
    {
        "id": "5234a7fe-881f-f0cb-0e7f-9dd22b8045e7",
        "code": "mts-mgw",
        "name": "Mangwe",
        "province_code": "MTS"
    },
    {
        "id": "3963de66-a9ff-871c-59db-d966f1c8926d",
        "code": "mts-mtb",
        "name": "Matobo",
        "province_code": "MTS"
    },
    {
        "id": "7baa68fb-709e-06b3-cf8b-3ed17172750c",
        "code": "mts-uzg",
        "name": "Umzingwane",
        "province_code": "MTS"
    },
    {
        "id": "0f8b8ce3-517e-02c1-18bd-37d66f51473f",
        "code": "mid-gwr",
        "name": "Gweru",
        "province_code": "MID"
    },
    {
        "id": "31622d7c-b71a-64a1-f018-6054b6cc2adb",
        "code": "mid-czi",
        "name": "Chirumhanzu",
        "province_code": "MID"
    },
    {
        "id": "9cb7f377-e72c-44ee-5b95-fbe0a2665220",
        "code": "mid-gkw",
        "name": "Gokwe North",
        "province_code": "MID"
    },
    {
        "id": "adfc1165-c353-6ce7-83d9-6a95dd52d39f",
        "code": "mid-gks",
        "name": "Gokwe South",
        "province_code": "MID"
    },
    {
        "id": "1ffd1f9c-3816-0c0f-271a-52de5782062f",
        "code": "mid-kwk",
        "name": "Kwekwe",
        "province_code": "MID"
    },
    {
        "id": "2eaa17e8-adc1-29dc-6e6b-6e6a68d81393",
        "code": "mid-mbr",
        "name": "Mberengwa",
        "province_code": "MID"
    },
    {
        "id": "119f40d2-879e-b3a5-9938-8441eec79c64",
        "code": "mid-shr",
        "name": "Shurugwi",
        "province_code": "MID"
    },
    {
        "id": "70158289-d62d-c45a-d497-65096a456145",
        "code": "mid-zvi",
        "name": "Zvishavane",
        "province_code": "MID"
    }
];

export const MOCK_SCHOOLS_NATIONAL: MockSchoolNational[] = [
    {
        "id": "9d4c6f94-4b74-6018-c173-e43a6b159bb4",
        "code": "SCH-BYO-01",
        "name": "Cornerstone High School",
        "province_code": "BYO",
        "district_code": "byo-cn",
        "type": "SECONDARY",
        "address": "Plot 35, Bulawayo Central",
        "phone": "+263715614226",
        "email": "info@cornerstone.edu.zw",
        "founded_year": 1973,
        "principal_name": "Clive Mhlanga",
        "total_students": 80,
        "boys": 48,
        "girls": 32,
        "total_teachers": 25,
        "total_classes": 8,
        "student_teacher_ratio": 3.2,
        "attendance_rate": 91.6,
        "average_mark": 64.3,
        "pass_rate": 85.1,
        "billed_usd": 53200.0,
        "collected_usd": 36314.5,
        "outstanding_usd": 16885.5,
        "collection_rate": 68.3,
        "payments_count": 89
    },
    {
        "id": "f9e97044-9d67-14ec-8092-502d8c644e2d",
        "code": "SCH-BYO-02",
        "name": "Lupane High School",
        "province_code": "BYO",
        "district_code": "byo-mp",
        "type": "SECONDARY",
        "address": "Plot 923, Mpopoma-Pelandaba",
        "phone": "+263712458591",
        "email": "info@lupane.edu.zw",
        "founded_year": 1995,
        "principal_name": "Learnmore Sibanda",
        "total_students": 80,
        "boys": 42,
        "girls": 38,
        "total_teachers": 25,
        "total_classes": 8,
        "student_teacher_ratio": 3.2,
        "attendance_rate": 90.8,
        "average_mark": 61.3,
        "pass_rate": 76.1,
        "billed_usd": 53200.0,
        "collected_usd": 36779.98,
        "outstanding_usd": 16420.02,
        "collection_rate": 69.1,
        "payments_count": 87
    },
    {
        "id": "9f7ebf3a-ed3e-0de9-ad70-31132f81db09",
        "code": "SCH-BYO-03",
        "name": "Chivhu Primary School",
        "province_code": "BYO",
        "district_code": "byo-nk",
        "type": "PRIMARY",
        "address": "Plot 248, Nkulumane",
        "phone": "+263719478454",
        "email": "info@chivhu.edu.zw",
        "founded_year": 1996,
        "principal_name": "Tafara Chari",
        "total_students": 80,
        "boys": 33,
        "girls": 47,
        "total_teachers": 25,
        "total_classes": 8,
        "student_teacher_ratio": 3.2,
        "attendance_rate": 92.0,
        "average_mark": 66.5,
        "pass_rate": 87.5,
        "billed_usd": 37200.0,
        "collected_usd": 24500.65,
        "outstanding_usd": 12699.35,
        "collection_rate": 65.9,
        "payments_count": 86
    },
    {
        "id": "16e64795-863e-caba-aa64-90e1e4fd43ec",
        "code": "SCH-BYO-04",
        "name": "Plumtree High School",
        "province_code": "BYO",
        "district_code": "byo-im",
        "type": "SECONDARY",
        "address": "Plot 728, Imbizo",
        "phone": "+263718038374",
        "email": "info@plumtree.edu.zw",
        "founded_year": 1972,
        "principal_name": "Liberty Gomba",
        "total_students": 80,
        "boys": 39,
        "girls": 41,
        "total_teachers": 25,
        "total_classes": 8,
        "student_teacher_ratio": 3.2,
        "attendance_rate": 92.6,
        "average_mark": 63.8,
        "pass_rate": 83.0,
        "billed_usd": 53200.0,
        "collected_usd": 37898.36,
        "outstanding_usd": 15301.64,
        "collection_rate": 71.2,
        "payments_count": 87
    },
    {
        "id": "fdb2e53b-6305-6360-6765-809fae7d76a5",
        "code": "SCH-BYO-05",
        "name": "Heritage High School",
        "province_code": "BYO",
        "district_code": "byo-rg",
        "type": "SECONDARY",
        "address": "Plot 16, Reigate",
        "phone": "+263713678638",
        "email": "info@heritage.edu.zw",
        "founded_year": 2002,
        "principal_name": "Learnmore Makoni",
        "total_students": 80,
        "boys": 39,
        "girls": 41,
        "total_teachers": 25,
        "total_classes": 8,
        "student_teacher_ratio": 3.2,
        "attendance_rate": 92.9,
        "average_mark": 61.3,
        "pass_rate": 76.9,
        "billed_usd": 53200.0,
        "collected_usd": 32269.02,
        "outstanding_usd": 20930.98,
        "collection_rate": 60.7,
        "payments_count": 83
    },
    {
        "id": "21f47472-300e-e40f-ceec-0abe7ca04bdd",
        "code": "SCH-BYO-06",
        "name": "Mzilikazi Primary School",
        "province_code": "BYO",
        "district_code": "byo-tj",
        "type": "PRIMARY",
        "address": "Plot 990, Tshabalala",
        "phone": "+263716647119",
        "email": "info@mzilikazi.edu.zw",
        "founded_year": 1964,
        "principal_name": "Tichaona Munyaradzi",
        "total_students": 80,
        "boys": 43,
        "girls": 37,
        "total_teachers": 25,
        "total_classes": 8,
        "student_teacher_ratio": 3.2,
        "attendance_rate": 92.3,
        "average_mark": 65.3,
        "pass_rate": 85.4,
        "billed_usd": 37200.0,
        "collected_usd": 25268.12,
        "outstanding_usd": 11931.88,
        "collection_rate": 67.9,
        "payments_count": 89
    },
    {
        "id": "a96d4166-2d0d-0250-334f-efe87b6d2840",
        "code": "SCH-HRE-01",
        "name": "Bindura Primary School",
        "province_code": "HRE",
        "district_code": "hre-cn",
        "type": "PRIMARY",
        "address": "Plot 362, Harare Central",
        "phone": "+263715437923",
        "email": "info@bindura.edu.zw",
        "founded_year": 2009,
        "principal_name": "Tinashe Mhembere",
        "total_students": 80,
        "boys": 44,
        "girls": 36,
        "total_teachers": 25,
        "total_classes": 8,
        "student_teacher_ratio": 3.2,
        "attendance_rate": 92.3,
        "average_mark": 63.4,
        "pass_rate": 81.9,
        "billed_usd": 37200.0,
        "collected_usd": 25906.72,
        "outstanding_usd": 11293.28,
        "collection_rate": 69.6,
        "payments_count": 85
    },
    {
        "id": "f3743dc0-a774-afaa-a35f-c05477b3dd39",
        "code": "SCH-HRE-02",
        "name": "Tsholotsho Primary School",
        "province_code": "HRE",
        "district_code": "hre-cb",
        "type": "PRIMARY",
        "address": "Plot 954, Chitungwiza",
        "phone": "+263717350753",
        "email": "info@tsholotsho.edu.zw",
        "founded_year": 1963,
        "principal_name": "Farai Maramba",
        "total_students": 80,
        "boys": 41,
        "girls": 39,
        "total_teachers": 25,
        "total_classes": 8,
        "student_teacher_ratio": 3.2,
        "attendance_rate": 92.7,
        "average_mark": 63.5,
        "pass_rate": 79.7,
        "billed_usd": 37200.0,
        "collected_usd": 26948.82,
        "outstanding_usd": 10251.18,
        "collection_rate": 72.4,
        "payments_count": 87
    },
    {
        "id": "5c36ee08-8eea-6ec0-6f21-5efaa3929e54",
        "code": "SCH-HRE-03",
        "name": "Nyanga High School",
        "province_code": "HRE",
        "district_code": "hre-ep",
        "type": "SECONDARY",
        "address": "Plot 380, Epworth",
        "phone": "+263714226067",
        "email": "info@nyanga.edu.zw",
        "founded_year": 2003,
        "principal_name": "Tonderai Sibanda",
        "total_students": 80,
        "boys": 41,
        "girls": 39,
        "total_teachers": 25,
        "total_classes": 8,
        "student_teacher_ratio": 3.2,
        "attendance_rate": 93.6,
        "average_mark": 61.5,
        "pass_rate": 76.6,
        "billed_usd": 53200.0,
        "collected_usd": 38373.37,
        "outstanding_usd": 14826.63,
        "collection_rate": 72.1,
        "payments_count": 99
    },
    {
        "id": "41fefce5-116b-9c12-f6f0-124b98ce8296",
        "code": "SCH-HRE-04",
        "name": "Founders High School",
        "province_code": "HRE",
        "district_code": "hre-mb",
        "type": "SECONDARY",
        "address": "Plot 91, Mbare-Hatfield",
        "phone": "+263714905582",
        "email": "info@founders.edu.zw",
        "founded_year": 2013,
        "principal_name": "Tawanda Munyaradzi",
        "total_students": 80,
        "boys": 43,
        "girls": 37,
        "total_teachers": 25,
        "total_classes": 8,
        "student_teacher_ratio": 3.2,
        "attendance_rate": 92.3,
        "average_mark": 65.6,
        "pass_rate": 87.7,
        "billed_usd": 53200.0,
        "collected_usd": 37145.66,
        "outstanding_usd": 16054.34,
        "collection_rate": 69.8,
        "payments_count": 82
    },
    {
        "id": "9ea0ced9-a201-c174-db78-df84d26ece83",
        "code": "SCH-HRE-05",
        "name": "Hwange High School",
        "province_code": "HRE",
        "district_code": "hre-gw",
        "type": "SECONDARY",
        "address": "Plot 864, Glen View-Mufakose",
        "phone": "+263717120868",
        "email": "info@hwange.edu.zw",
        "founded_year": 1968,
        "principal_name": "Innocent Maguwu",
        "total_students": 80,
        "boys": 42,
        "girls": 38,
        "total_teachers": 25,
        "total_classes": 8,
        "student_teacher_ratio": 3.2,
        "attendance_rate": 92.7,
        "average_mark": 64.8,
        "pass_rate": 85.7,
        "billed_usd": 53200.0,
        "collected_usd": 38643.82,
        "outstanding_usd": 14556.18,
        "collection_rate": 72.6,
        "payments_count": 88
    },
    {
        "id": "d2d87fbb-ac1f-c0ef-f938-63a2e9f8cde0",
        "code": "SCH-HRE-06",
        "name": "Mutare High School",
        "province_code": "HRE",
        "district_code": "hre-kk",
        "type": "SECONDARY",
        "address": "Plot 728, Kuwadzana-Warren",
        "phone": "+263712197935",
        "email": "info@mutare.edu.zw",
        "founded_year": 1996,
        "principal_name": "Brian Manyika",
        "total_students": 80,
        "boys": 43,
        "girls": 37,
        "total_teachers": 25,
        "total_classes": 8,
        "student_teacher_ratio": 3.2,
        "attendance_rate": 92.0,
        "average_mark": 64.4,
        "pass_rate": 82.3,
        "billed_usd": 53200.0,
        "collected_usd": 37336.55,
        "outstanding_usd": 15863.45,
        "collection_rate": 70.2,
        "payments_count": 91
    },
    {
        "id": "5896bdee-7cf2-fcee-70f0-da8b31b6c7b9",
        "code": "SCH-MAN-01",
        "name": "St. Peter's Primary School",
        "province_code": "MAN",
        "district_code": "man-mtc",
        "type": "PRIMARY",
        "address": "Plot 398, Mutare City",
        "phone": "+263715528972",
        "email": "info@stpeters.edu.zw",
        "founded_year": 2017,
        "principal_name": "Clive Mandaza",
        "total_students": 80,
        "boys": 41,
        "girls": 39,
        "total_teachers": 25,
        "total_classes": 8,
        "student_teacher_ratio": 3.2,
        "attendance_rate": 91.0,
        "average_mark": 64.8,
        "pass_rate": 85.2,
        "billed_usd": 37200.0,
        "collected_usd": 26667.17,
        "outstanding_usd": 10532.83,
        "collection_rate": 71.7,
        "payments_count": 93
    },
    {
        "id": "ca01ee94-d011-24e6-0bcc-e976a1c807e2",
        "code": "SCH-MAN-02",
        "name": "Murewa Primary School",
        "province_code": "MAN",
        "district_code": "man-mtr",
        "type": "PRIMARY",
        "address": "Plot 42, Mutare Rural",
        "phone": "+263716292423",
        "email": "info@murewa.edu.zw",
        "founded_year": 1983,
        "principal_name": "Emmanuel Dube",
        "total_students": 80,
        "boys": 43,
        "girls": 37,
        "total_teachers": 25,
        "total_classes": 8,
        "student_teacher_ratio": 3.2,
        "attendance_rate": 91.7,
        "average_mark": 67.4,
        "pass_rate": 89.6,
        "billed_usd": 37200.0,
        "collected_usd": 24262.55,
        "outstanding_usd": 12937.45,
        "collection_rate": 65.2,
        "payments_count": 80
    },
    {
        "id": "732563dc-be62-8524-d52f-93d23b2d3336",
        "code": "SCH-MAN-03",
        "name": "Kariba High School",
        "province_code": "MAN",
        "district_code": "man-bua",
        "type": "SECONDARY",
        "address": "Plot 590, Buhera",
        "phone": "+263716279418",
        "email": "info@kariba.edu.zw",
        "founded_year": 1971,
        "principal_name": "Pardon Madondo",
        "total_students": 80,
        "boys": 38,
        "girls": 42,
        "total_teachers": 25,
        "total_classes": 8,
        "student_teacher_ratio": 3.2,
        "attendance_rate": 92.2,
        "average_mark": 66.0,
        "pass_rate": 88.0,
        "billed_usd": 53200.0,
        "collected_usd": 37294.67,
        "outstanding_usd": 15905.33,
        "collection_rate": 70.1,
        "payments_count": 94
    },
    {
        "id": "35e6eb63-32ba-7b8c-92b3-00ac7f8118dc",
        "code": "SCH-MAN-04",
        "name": "Beitbridge Primary School",
        "province_code": "MAN",
        "district_code": "man-chm",
        "type": "PRIMARY",
        "address": "Plot 152, Chimanimani",
        "phone": "+263715137722",
        "email": "info@beitbridge.edu.zw",
        "founded_year": 2005,
        "principal_name": "Edmore Gomba",
        "total_students": 80,
        "boys": 43,
        "girls": 37,
        "total_teachers": 25,
        "total_classes": 8,
        "student_teacher_ratio": 3.2,
        "attendance_rate": 92.1,
        "average_mark": 62.7,
        "pass_rate": 82.5,
        "billed_usd": 37200.0,
        "collected_usd": 27983.72,
        "outstanding_usd": 9216.28,
        "collection_rate": 75.2,
        "payments_count": 90
    },
    {
        "id": "9a5fa2aa-68d5-dfe1-e0a0-babb2808a48e",
        "code": "SCH-MAN-05",
        "name": "Esigodini High School",
        "province_code": "MAN",
        "district_code": "man-chp",
        "type": "SECONDARY",
        "address": "Plot 418, Chipinge",
        "phone": "+263717073292",
        "email": "info@esigodini.edu.zw",
        "founded_year": 1972,
        "principal_name": "Tonderai Marufu",
        "total_students": 80,
        "boys": 40,
        "girls": 40,
        "total_teachers": 25,
        "total_classes": 8,
        "student_teacher_ratio": 3.2,
        "attendance_rate": 91.1,
        "average_mark": 63.8,
        "pass_rate": 82.9,
        "billed_usd": 53200.0,
        "collected_usd": 35202.17,
        "outstanding_usd": 17997.83,
        "collection_rate": 66.2,
        "payments_count": 81
    },
    {
        "id": "32590e72-67b1-5003-c18d-cd7fb45c1581",
        "code": "SCH-MAN-06",
        "name": "Vision Primary School",
        "province_code": "MAN",
        "district_code": "man-mks",
        "type": "PRIMARY",
        "address": "Plot 58, Makoni",
        "phone": "+263712839607",
        "email": "info@vision.edu.zw",
        "founded_year": 1967,
        "principal_name": "Brian Maposa",
        "total_students": 80,
        "boys": 40,
        "girls": 40,
        "total_teachers": 25,
        "total_classes": 8,
        "student_teacher_ratio": 3.2,
        "attendance_rate": 92.3,
        "average_mark": 61.7,
        "pass_rate": 79.7,
        "billed_usd": 37200.0,
        "collected_usd": 27442.08,
        "outstanding_usd": 9757.92,
        "collection_rate": 73.8,
        "payments_count": 98
    },
    {
        "id": "47eb430f-4604-a4a6-2e3f-6590e97d751f",
        "code": "SCH-MCE-01",
        "name": "Kwekwe Primary School",
        "province_code": "MCE",
        "district_code": "mce-bnd",
        "type": "PRIMARY",
        "address": "Plot 400, Bindura",
        "phone": "+263718852574",
        "email": "info@kwekwe.edu.zw",
        "founded_year": 1991,
        "principal_name": "Edmore Chari",
        "total_students": 80,
        "boys": 34,
        "girls": 46,
        "total_teachers": 25,
        "total_classes": 8,
        "student_teacher_ratio": 3.2,
        "attendance_rate": 91.2,
        "average_mark": 65.5,
        "pass_rate": 85.0,
        "billed_usd": 37200.0,
        "collected_usd": 29049.55,
        "outstanding_usd": 8150.45,
        "collection_rate": 78.1,
        "payments_count": 100
    },
    {
        "id": "3b2f70e7-d016-7ca4-dbec-921e18ed5456",
        "code": "SCH-MCE-02",
        "name": "Marondera High School",
        "province_code": "MCE",
        "district_code": "mce-cnt",
        "type": "SECONDARY",
        "address": "Plot 127, Centenary",
        "phone": "+263715476583",
        "email": "info@marondera.edu.zw",
        "founded_year": 2007,
        "principal_name": "Hardlife Nyathi",
        "total_students": 80,
        "boys": 45,
        "girls": 35,
        "total_teachers": 25,
        "total_classes": 8,
        "student_teacher_ratio": 3.2,
        "attendance_rate": 93.0,
        "average_mark": 63.7,
        "pass_rate": 83.1,
        "billed_usd": 53200.0,
        "collected_usd": 37746.76,
        "outstanding_usd": 15453.24,
        "collection_rate": 71.0,
        "payments_count": 83
    },
    {
        "id": "8c420a15-d31a-99d7-a611-932025871514",
        "code": "SCH-MCE-03",
        "name": "Gwanda High School",
        "province_code": "MCE",
        "district_code": "mce-gku",
        "type": "SECONDARY",
        "address": "Plot 474, Guruve",
        "phone": "+263711054447",
        "email": "info@gwanda.edu.zw",
        "founded_year": 2004,
        "principal_name": "Edmore Marufu",
        "total_students": 80,
        "boys": 45,
        "girls": 35,
        "total_teachers": 25,
        "total_classes": 8,
        "student_teacher_ratio": 3.2,
        "attendance_rate": 91.4,
        "average_mark": 63.9,
        "pass_rate": 83.3,
        "billed_usd": 53200.0,
        "collected_usd": 36223.31,
        "outstanding_usd": 16976.69,
        "collection_rate": 68.1,
        "payments_count": 83
    },
    {
        "id": "0ad317e0-f481-d232-0d60-dc2b315a8d8d",
        "code": "SCH-MCE-04",
        "name": "Mt. Pleasant High School",
        "province_code": "MCE",
        "district_code": "mce-mke",
        "type": "SECONDARY",
        "address": "Plot 118, Mazowe",
        "phone": "+263716007072",
        "email": "info@mtpleasant.edu.zw",
        "founded_year": 2011,
        "principal_name": "Privilege Kanengoni",
        "total_students": 80,
        "boys": 30,
        "girls": 50,
        "total_teachers": 25,
        "total_classes": 8,
        "student_teacher_ratio": 3.2,
        "attendance_rate": 92.8,
        "average_mark": 63.5,
        "pass_rate": 81.1,
        "billed_usd": 53200.0,
        "collected_usd": 35551.12,
        "outstanding_usd": 17648.88,
        "collection_rate": 66.8,
        "payments_count": 72
    },
    {
        "id": "11d470ee-6f55-5351-40a8-3a51fa1ff8e0",
        "code": "SCH-MCE-05",
        "name": "Pumula Primary School",
        "province_code": "MCE",
        "district_code": "mce-mbi",
        "type": "PRIMARY",
        "address": "Plot 790, Mbire",
        "phone": "+263713710343",
        "email": "info@pumula.edu.zw",
        "founded_year": 1992,
        "principal_name": "Tinotenda Moyo",
        "total_students": 80,
        "boys": 44,
        "girls": 36,
        "total_teachers": 25,
        "total_classes": 8,
        "student_teacher_ratio": 3.2,
        "attendance_rate": 91.6,
        "average_mark": 64.3,
        "pass_rate": 84.5,
        "billed_usd": 37200.0,
        "collected_usd": 27385.12,
        "outstanding_usd": 9814.88,
        "collection_rate": 73.6,
        "payments_count": 89
    },
    {
        "id": "a7851e16-ec2d-cfec-b494-326ed8155586",
        "code": "SCH-MCE-06",
        "name": "Chinhoyi Primary School",
        "province_code": "MCE",
        "district_code": "mce-mtk",
        "type": "PRIMARY",
        "address": "Plot 29, Mt Darwin",
        "phone": "+263712876828",
        "email": "info@chinhoyi.edu.zw",
        "founded_year": 2017,
        "principal_name": "Innocent Zimuto",
        "total_students": 80,
        "boys": 46,
        "girls": 34,
        "total_teachers": 25,
        "total_classes": 8,
        "student_teacher_ratio": 3.2,
        "attendance_rate": 92.0,
        "average_mark": 63.1,
        "pass_rate": 82.3,
        "billed_usd": 37200.0,
        "collected_usd": 24863.13,
        "outstanding_usd": 12336.87,
        "collection_rate": 66.8,
        "payments_count": 87
    },
    {
        "id": "2523e570-59a4-1199-7797-04bdd56b999e",
        "code": "SCH-MEA-01",
        "name": "Nkayi Primary School",
        "province_code": "MEA",
        "district_code": "mea-mrn",
        "type": "PRIMARY",
        "address": "Plot 909, Marondera",
        "phone": "+263712321324",
        "email": "info@nkayi.edu.zw",
        "founded_year": 1963,
        "principal_name": "Pardon Dube",
        "total_students": 80,
        "boys": 42,
        "girls": 38,
        "total_teachers": 25,
        "total_classes": 8,
        "student_teacher_ratio": 3.2,
        "attendance_rate": 91.7,
        "average_mark": 64.1,
        "pass_rate": 87.1,
        "billed_usd": 37200.0,
        "collected_usd": 24907.3,
        "outstanding_usd": 12292.7,
        "collection_rate": 67.0,
        "payments_count": 92
    },
    {
        "id": "a1373878-562b-1918-4df8-36d654efbb1d",
        "code": "SCH-MEA-02",
        "name": "Mufakose High School",
        "province_code": "MEA",
        "district_code": "mea-chk",
        "type": "SECONDARY",
        "address": "Plot 141, Chikomba",
        "phone": "+263718973915",
        "email": "info@mufakose.edu.zw",
        "founded_year": 2018,
        "principal_name": "Brian Mudenda",
        "total_students": 80,
        "boys": 37,
        "girls": 43,
        "total_teachers": 25,
        "total_classes": 8,
        "student_teacher_ratio": 3.2,
        "attendance_rate": 90.8,
        "average_mark": 61.9,
        "pass_rate": 78.6,
        "billed_usd": 53200.0,
        "collected_usd": 35811.34,
        "outstanding_usd": 17388.66,
        "collection_rate": 67.3,
        "payments_count": 81
    },
    {
        "id": "4bfec7c8-a158-a47e-ab0d-b81c5d724383",
        "code": "SCH-MEA-03",
        "name": "Goromonzi High School",
        "province_code": "MEA",
        "district_code": "mea-grr",
        "type": "SECONDARY",
        "address": "Plot 443, Goromonzi",
        "phone": "+263714553384",
        "email": "info@goromonzi.edu.zw",
        "founded_year": 2017,
        "principal_name": "Blessing Zimuto",
        "total_students": 80,
        "boys": 37,
        "girls": 43,
        "total_teachers": 25,
        "total_classes": 8,
        "student_teacher_ratio": 3.2,
        "attendance_rate": 92.3,
        "average_mark": 62.2,
        "pass_rate": 81.3,
        "billed_usd": 53200.0,
        "collected_usd": 34300.26,
        "outstanding_usd": 18899.74,
        "collection_rate": 64.5,
        "payments_count": 81
    },
    {
        "id": "43e3f5a2-9a78-2c1d-e769-193a72b7efd0",
        "code": "SCH-MEA-04",
        "name": "Glen View High School",
        "province_code": "MEA",
        "district_code": "mea-htf",
        "type": "SECONDARY",
        "address": "Plot 675, Hwedza",
        "phone": "+263717264956",
        "email": "info@glenview.edu.zw",
        "founded_year": 1986,
        "principal_name": "Tinotenda Mapfumo",
        "total_students": 80,
        "boys": 40,
        "girls": 40,
        "total_teachers": 25,
        "total_classes": 8,
        "student_teacher_ratio": 3.2,
        "attendance_rate": 93.5,
        "average_mark": 65.0,
        "pass_rate": 84.6,
        "billed_usd": 53200.0,
        "collected_usd": 42525.63,
        "outstanding_usd": 10674.37,
        "collection_rate": 79.9,
        "payments_count": 87
    },
    {
        "id": "0d0ecb01-9a22-ff65-7683-ca9926ce4910",
        "code": "SCH-MEA-05",
        "name": "Chiredzi Primary School",
        "province_code": "MEA",
        "district_code": "mea-mds",
        "type": "PRIMARY",
        "address": "Plot 75, Mudzi",
        "phone": "+263716672134",
        "email": "info@chiredzi.edu.zw",
        "founded_year": 1959,
        "principal_name": "Clive Gomba",
        "total_students": 80,
        "boys": 44,
        "girls": 36,
        "total_teachers": 25,
        "total_classes": 8,
        "student_teacher_ratio": 3.2,
        "attendance_rate": 93.0,
        "average_mark": 64.3,
        "pass_rate": 84.2,
        "billed_usd": 37200.0,
        "collected_usd": 25241.59,
        "outstanding_usd": 11958.41,
        "collection_rate": 67.9,
        "payments_count": 99
    },
    {
        "id": "d29b5765-5d85-d3bf-4493-34a0df852f5b",
        "code": "SCH-MEA-06",
        "name": "St. Mary's Primary School",
        "province_code": "MEA",
        "district_code": "mea-msh",
        "type": "PRIMARY",
        "address": "Plot 734, Murehwa",
        "phone": "+263711987737",
        "email": "info@stmarys.edu.zw",
        "founded_year": 1972,
        "principal_name": "Tonderai Sibanda",
        "total_students": 80,
        "boys": 41,
        "girls": 39,
        "total_teachers": 25,
        "total_classes": 8,
        "student_teacher_ratio": 3.2,
        "attendance_rate": 92.2,
        "average_mark": 63.7,
        "pass_rate": 78.3,
        "billed_usd": 37200.0,
        "collected_usd": 26871.82,
        "outstanding_usd": 10328.18,
        "collection_rate": 72.2,
        "payments_count": 92
    },
    {
        "id": "9dbe4fb9-274a-48dd-4fe5-031854b50a9e",
        "code": "SCH-MWE-01",
        "name": "Cornerstone Primary School",
        "province_code": "MWE",
        "district_code": "mwe-chn",
        "type": "PRIMARY",
        "address": "Plot 253, Chinhoyi",
        "phone": "+263715672073",
        "email": "info@cornerstone.edu.zw",
        "founded_year": 2000,
        "principal_name": "Pardon Mugabe",
        "total_students": 80,
        "boys": 35,
        "girls": 45,
        "total_teachers": 25,
        "total_classes": 8,
        "student_teacher_ratio": 3.2,
        "attendance_rate": 92.1,
        "average_mark": 63.0,
        "pass_rate": 80.9,
        "billed_usd": 37200.0,
        "collected_usd": 24767.7,
        "outstanding_usd": 12432.3,
        "collection_rate": 66.6,
        "payments_count": 88
    },
    {
        "id": "b15054f4-6e32-8a18-7ff5-52cd7114ba3b",
        "code": "SCH-MWE-02",
        "name": "Lupane Primary School",
        "province_code": "MWE",
        "district_code": "mwe-chg",
        "type": "PRIMARY",
        "address": "Plot 967, Chegutu",
        "phone": "+263718930103",
        "email": "info@lupane.edu.zw",
        "founded_year": 1973,
        "principal_name": "Munyaradzi Madziva",
        "total_students": 80,
        "boys": 43,
        "girls": 37,
        "total_teachers": 25,
        "total_classes": 8,
        "student_teacher_ratio": 3.2,
        "attendance_rate": 91.9,
        "average_mark": 61.9,
        "pass_rate": 80.3,
        "billed_usd": 37200.0,
        "collected_usd": 27468.56,
        "outstanding_usd": 9731.44,
        "collection_rate": 73.8,
        "payments_count": 99
    },
    {
        "id": "b7d10b70-6995-acce-3edb-5abd52d1034d",
        "code": "SCH-MWE-03",
        "name": "Chivhu Primary School",
        "province_code": "MWE",
        "district_code": "mwe-hrr",
        "type": "PRIMARY",
        "address": "Plot 684, Hurungwe",
        "phone": "+263718231838",
        "email": "info@chivhu.edu.zw",
        "founded_year": 1980,
        "principal_name": "Learnmore Madziva",
        "total_students": 80,
        "boys": 38,
        "girls": 42,
        "total_teachers": 25,
        "total_classes": 8,
        "student_teacher_ratio": 3.2,
        "attendance_rate": 92.0,
        "average_mark": 64.8,
        "pass_rate": 84.3,
        "billed_usd": 37200.0,
        "collected_usd": 25631.67,
        "outstanding_usd": 11568.33,
        "collection_rate": 68.9,
        "payments_count": 92
    },
    {
        "id": "e866ee35-9998-9f44-8cc6-c9c27534c345",
        "code": "SCH-MWE-04",
        "name": "Plumtree High School",
        "province_code": "MWE",
        "district_code": "mwe-krb",
        "type": "SECONDARY",
        "address": "Plot 65, Kariba",
        "phone": "+263712651177",
        "email": "info@plumtree.edu.zw",
        "founded_year": 1961,
        "principal_name": "Justice Makoni",
        "total_students": 80,
        "boys": 36,
        "girls": 44,
        "total_teachers": 25,
        "total_classes": 8,
        "student_teacher_ratio": 3.2,
        "attendance_rate": 93.3,
        "average_mark": 62.2,
        "pass_rate": 81.3,
        "billed_usd": 53200.0,
        "collected_usd": 37170.96,
        "outstanding_usd": 16029.04,
        "collection_rate": 69.9,
        "payments_count": 87
    },
    {
        "id": "c878f6d4-20c0-bc3c-3ed1-0f7dd475255f",
        "code": "SCH-MWE-05",
        "name": "Heritage Primary School",
        "province_code": "MWE",
        "district_code": "mwe-mkd",
        "type": "PRIMARY",
        "address": "Plot 204, Makonde",
        "phone": "+263719997381",
        "email": "info@heritage.edu.zw",
        "founded_year": 1986,
        "principal_name": "Tonderai Maposa",
        "total_students": 80,
        "boys": 40,
        "girls": 40,
        "total_teachers": 25,
        "total_classes": 8,
        "student_teacher_ratio": 3.2,
        "attendance_rate": 91.9,
        "average_mark": 64.5,
        "pass_rate": 84.0,
        "billed_usd": 37200.0,
        "collected_usd": 24773.36,
        "outstanding_usd": 12426.64,
        "collection_rate": 66.6,
        "payments_count": 85
    },
    {
        "id": "4a623671-a0a1-54b9-c5e9-685418743d6b",
        "code": "SCH-MWE-06",
        "name": "Mzilikazi Primary School",
        "province_code": "MWE",
        "district_code": "mwe-mhd",
        "type": "PRIMARY",
        "address": "Plot 265, Mhondoro-Ngezi",
        "phone": "+263712264748",
        "email": "info@mzilikazi.edu.zw",
        "founded_year": 1986,
        "principal_name": "Tawanda Ndlovu",
        "total_students": 80,
        "boys": 35,
        "girls": 45,
        "total_teachers": 25,
        "total_classes": 8,
        "student_teacher_ratio": 3.2,
        "attendance_rate": 92.0,
        "average_mark": 63.1,
        "pass_rate": 79.8,
        "billed_usd": 37200.0,
        "collected_usd": 26700.97,
        "outstanding_usd": 10499.03,
        "collection_rate": 71.8,
        "payments_count": 88
    },
    {
        "id": "0bd14fb1-87ee-d7ee-5e90-3cc8c9b03554",
        "code": "SCH-MAS-01",
        "name": "Bindura High School",
        "province_code": "MAS",
        "district_code": "mas-msv",
        "type": "SECONDARY",
        "address": "Plot 105, Masvingo",
        "phone": "+263714965789",
        "email": "info@bindura.edu.zw",
        "founded_year": 1968,
        "principal_name": "Knowledge Mawere",
        "total_students": 80,
        "boys": 43,
        "girls": 37,
        "total_teachers": 25,
        "total_classes": 8,
        "student_teacher_ratio": 3.2,
        "attendance_rate": 92.4,
        "average_mark": 64.3,
        "pass_rate": 83.6,
        "billed_usd": 53200.0,
        "collected_usd": 41990.95,
        "outstanding_usd": 11209.05,
        "collection_rate": 78.9,
        "payments_count": 91
    },
    {
        "id": "88d6d88c-70fd-1210-1290-b44a1143056a",
        "code": "SCH-MAS-02",
        "name": "Tsholotsho Primary School",
        "province_code": "MAS",
        "district_code": "mas-bks",
        "type": "PRIMARY",
        "address": "Plot 420, Bikita",
        "phone": "+263711983738",
        "email": "info@tsholotsho.edu.zw",
        "founded_year": 1968,
        "principal_name": "Itai Moyo",
        "total_students": 80,
        "boys": 41,
        "girls": 39,
        "total_teachers": 25,
        "total_classes": 8,
        "student_teacher_ratio": 3.2,
        "attendance_rate": 91.7,
        "average_mark": 64.3,
        "pass_rate": 81.8,
        "billed_usd": 37200.0,
        "collected_usd": 27278.43,
        "outstanding_usd": 9921.57,
        "collection_rate": 73.3,
        "payments_count": 93
    },
    {
        "id": "be26387c-da2a-e85f-a7ae-11d39a8cb5a8",
        "code": "SCH-MAS-03",
        "name": "Nyanga Primary School",
        "province_code": "MAS",
        "district_code": "mas-cdz",
        "type": "PRIMARY",
        "address": "Plot 812, Chiredzi",
        "phone": "+263718633773",
        "email": "info@nyanga.edu.zw",
        "founded_year": 1976,
        "principal_name": "Learnmore Chari",
        "total_students": 80,
        "boys": 48,
        "girls": 32,
        "total_teachers": 25,
        "total_classes": 8,
        "student_teacher_ratio": 3.2,
        "attendance_rate": 92.5,
        "average_mark": 62.5,
        "pass_rate": 78.7,
        "billed_usd": 37200.0,
        "collected_usd": 24648.93,
        "outstanding_usd": 12551.07,
        "collection_rate": 66.3,
        "payments_count": 86
    },
    {
        "id": "26b051c6-32cd-f8ef-a7b6-8ceeb7741dd5",
        "code": "SCH-MAS-04",
        "name": "Founders Primary School",
        "province_code": "MAS",
        "district_code": "mas-civ",
        "type": "PRIMARY",
        "address": "Plot 313, Chivi",
        "phone": "+263714652414",
        "email": "info@founders.edu.zw",
        "founded_year": 1961,
        "principal_name": "Tatenda Mandaza",
        "total_students": 80,
        "boys": 39,
        "girls": 41,
        "total_teachers": 25,
        "total_classes": 8,
        "student_teacher_ratio": 3.2,
        "attendance_rate": 92.1,
        "average_mark": 62.9,
        "pass_rate": 84.2,
        "billed_usd": 37200.0,
        "collected_usd": 24932.22,
        "outstanding_usd": 12267.78,
        "collection_rate": 67.0,
        "payments_count": 82
    },
    {
        "id": "3c850ed0-0ef6-d342-69dc-a0b186f79338",
        "code": "SCH-MAS-05",
        "name": "Hwange Primary School",
        "province_code": "MAS",
        "district_code": "mas-grj",
        "type": "PRIMARY",
        "address": "Plot 498, Gutu",
        "phone": "+263719436429",
        "email": "info@hwange.edu.zw",
        "founded_year": 2016,
        "principal_name": "Tinotenda Chigumba",
        "total_students": 80,
        "boys": 45,
        "girls": 35,
        "total_teachers": 25,
        "total_classes": 8,
        "student_teacher_ratio": 3.2,
        "attendance_rate": 91.7,
        "average_mark": 62.9,
        "pass_rate": 82.0,
        "billed_usd": 37200.0,
        "collected_usd": 24854.68,
        "outstanding_usd": 12345.32,
        "collection_rate": 66.8,
        "payments_count": 83
    },
    {
        "id": "b0b7d124-1946-2506-7a0a-a273970e1af1",
        "code": "SCH-MAS-06",
        "name": "Mutare High School",
        "province_code": "MAS",
        "district_code": "mas-mhk",
        "type": "SECONDARY",
        "address": "Plot 92, Mwenezi",
        "phone": "+263714117625",
        "email": "info@mutare.edu.zw",
        "founded_year": 1962,
        "principal_name": "Tonderai Chinhoyi",
        "total_students": 80,
        "boys": 40,
        "girls": 40,
        "total_teachers": 25,
        "total_classes": 8,
        "student_teacher_ratio": 3.2,
        "attendance_rate": 93.0,
        "average_mark": 63.7,
        "pass_rate": 84.2,
        "billed_usd": 53200.0,
        "collected_usd": 33950.56,
        "outstanding_usd": 19249.44,
        "collection_rate": 63.8,
        "payments_count": 85
    },
    {
        "id": "6cafec94-f21c-42b0-4184-7bcb04af5b40",
        "code": "SCH-MTN-01",
        "name": "St. Peter's Primary School",
        "province_code": "MTN",
        "district_code": "mtn-lpe",
        "type": "PRIMARY",
        "address": "Plot 921, Lupane",
        "phone": "+263715130808",
        "email": "info@stpeters.edu.zw",
        "founded_year": 1995,
        "principal_name": "Tinashe Kapfumvuti",
        "total_students": 80,
        "boys": 39,
        "girls": 41,
        "total_teachers": 25,
        "total_classes": 8,
        "student_teacher_ratio": 3.2,
        "attendance_rate": 91.8,
        "average_mark": 64.9,
        "pass_rate": 81.5,
        "billed_usd": 37200.0,
        "collected_usd": 26689.28,
        "outstanding_usd": 10510.72,
        "collection_rate": 71.7,
        "payments_count": 88
    },
    {
        "id": "e06302dc-9de7-f705-966a-abd9696bbee4",
        "code": "SCH-MTN-02",
        "name": "Murewa High School",
        "province_code": "MTN",
        "district_code": "mtn-bbk",
        "type": "SECONDARY",
        "address": "Plot 607, Binga",
        "phone": "+263719770838",
        "email": "info@murewa.edu.zw",
        "founded_year": 1978,
        "principal_name": "Edmore Mugabe",
        "total_students": 80,
        "boys": 38,
        "girls": 42,
        "total_teachers": 25,
        "total_classes": 8,
        "student_teacher_ratio": 3.2,
        "attendance_rate": 90.8,
        "average_mark": 64.0,
        "pass_rate": 82.0,
        "billed_usd": 53200.0,
        "collected_usd": 39051.47,
        "outstanding_usd": 14148.53,
        "collection_rate": 73.4,
        "payments_count": 94
    },
    {
        "id": "1d1e8ed1-5d89-1f1c-4a2a-e972980e260b",
        "code": "SCH-MTN-03",
        "name": "Kariba Primary School",
        "province_code": "MTN",
        "district_code": "mtn-bbg",
        "type": "PRIMARY",
        "address": "Plot 415, Bubi",
        "phone": "+263713195773",
        "email": "info@kariba.edu.zw",
        "founded_year": 2000,
        "principal_name": "Garikai Mhembere",
        "total_students": 80,
        "boys": 29,
        "girls": 51,
        "total_teachers": 25,
        "total_classes": 8,
        "student_teacher_ratio": 3.2,
        "attendance_rate": 92.7,
        "average_mark": 65.2,
        "pass_rate": 86.0,
        "billed_usd": 37200.0,
        "collected_usd": 26192.88,
        "outstanding_usd": 11007.12,
        "collection_rate": 70.4,
        "payments_count": 85
    },
    {
        "id": "2c0387d7-3614-8d01-826f-0b3ff317231c",
        "code": "SCH-MTN-04",
        "name": "Beitbridge High School",
        "province_code": "MTN",
        "district_code": "mtn-hwg",
        "type": "SECONDARY",
        "address": "Plot 968, Hwange",
        "phone": "+263712217071",
        "email": "info@beitbridge.edu.zw",
        "founded_year": 1958,
        "principal_name": "Munashe Kapfumvuti",
        "total_students": 80,
        "boys": 39,
        "girls": 41,
        "total_teachers": 25,
        "total_classes": 8,
        "student_teacher_ratio": 3.2,
        "attendance_rate": 92.4,
        "average_mark": 63.3,
        "pass_rate": 81.2,
        "billed_usd": 53200.0,
        "collected_usd": 37928.99,
        "outstanding_usd": 15271.01,
        "collection_rate": 71.3,
        "payments_count": 86
    },
    {
        "id": "8b93c7fa-ceb4-3846-4a97-3850d8a488b7",
        "code": "SCH-MTN-05",
        "name": "Esigodini High School",
        "province_code": "MTN",
        "district_code": "mtn-nkb",
        "type": "SECONDARY",
        "address": "Plot 85, Nkayi",
        "phone": "+263714576135",
        "email": "info@esigodini.edu.zw",
        "founded_year": 1990,
        "principal_name": "Edmore Mhlanga",
        "total_students": 80,
        "boys": 43,
        "girls": 37,
        "total_teachers": 25,
        "total_classes": 8,
        "student_teacher_ratio": 3.2,
        "attendance_rate": 91.7,
        "average_mark": 63.7,
        "pass_rate": 83.7,
        "billed_usd": 53200.0,
        "collected_usd": 34312.45,
        "outstanding_usd": 18887.55,
        "collection_rate": 64.5,
        "payments_count": 77
    },
    {
        "id": "4e28586e-4c8f-768c-4007-fde194d2a8ab",
        "code": "SCH-MTN-06",
        "name": "Vision High School",
        "province_code": "MTN",
        "district_code": "mtn-tsh",
        "type": "SECONDARY",
        "address": "Plot 910, Tsholotsho",
        "phone": "+263715098412",
        "email": "info@vision.edu.zw",
        "founded_year": 1981,
        "principal_name": "Farai Chigumba",
        "total_students": 80,
        "boys": 47,
        "girls": 33,
        "total_teachers": 25,
        "total_classes": 8,
        "student_teacher_ratio": 3.2,
        "attendance_rate": 92.0,
        "average_mark": 65.9,
        "pass_rate": 87.4,
        "billed_usd": 53200.0,
        "collected_usd": 40189.85,
        "outstanding_usd": 13010.15,
        "collection_rate": 75.5,
        "payments_count": 85
    },
    {
        "id": "179a8c01-199c-3ae4-5327-5a10bba8b700",
        "code": "SCH-MTS-01",
        "name": "Kwekwe High School",
        "province_code": "MTS",
        "district_code": "mts-gwd",
        "type": "SECONDARY",
        "address": "Plot 730, Gwanda",
        "phone": "+263716075395",
        "email": "info@kwekwe.edu.zw",
        "founded_year": 1997,
        "principal_name": "Tinotenda Moyo",
        "total_students": 80,
        "boys": 41,
        "girls": 39,
        "total_teachers": 25,
        "total_classes": 8,
        "student_teacher_ratio": 3.2,
        "attendance_rate": 91.4,
        "average_mark": 63.5,
        "pass_rate": 84.3,
        "billed_usd": 53200.0,
        "collected_usd": 37081.47,
        "outstanding_usd": 16118.53,
        "collection_rate": 69.7,
        "payments_count": 89
    },
    {
        "id": "59e8aa81-82d7-5164-16cf-57f7ffa4f942",
        "code": "SCH-MTS-02",
        "name": "Marondera Primary School",
        "province_code": "MTS",
        "district_code": "mts-bei",
        "type": "PRIMARY",
        "address": "Plot 689, Beitbridge",
        "phone": "+263712737893",
        "email": "info@marondera.edu.zw",
        "founded_year": 2018,
        "principal_name": "Tonderai Mudenda",
        "total_students": 80,
        "boys": 42,
        "girls": 38,
        "total_teachers": 25,
        "total_classes": 8,
        "student_teacher_ratio": 3.2,
        "attendance_rate": 92.6,
        "average_mark": 63.0,
        "pass_rate": 82.7,
        "billed_usd": 37200.0,
        "collected_usd": 23262.64,
        "outstanding_usd": 13937.36,
        "collection_rate": 62.5,
        "payments_count": 83
    },
    {
        "id": "9aed300f-ecf7-8178-3674-26c9f9c19b17",
        "code": "SCH-MTS-03",
        "name": "Gwanda High School",
        "province_code": "MTS",
        "district_code": "mts-bmb",
        "type": "SECONDARY",
        "address": "Plot 770, Bulilima",
        "phone": "+263713607983",
        "email": "info@gwanda.edu.zw",
        "founded_year": 1975,
        "principal_name": "Farai Kanengoni",
        "total_students": 80,
        "boys": 36,
        "girls": 44,
        "total_teachers": 25,
        "total_classes": 8,
        "student_teacher_ratio": 3.2,
        "attendance_rate": 92.9,
        "average_mark": 65.5,
        "pass_rate": 86.0,
        "billed_usd": 53200.0,
        "collected_usd": 37002.81,
        "outstanding_usd": 16197.19,
        "collection_rate": 69.6,
        "payments_count": 92
    },
    {
        "id": "b06c3067-77d2-c78d-a693-979249f18514",
        "code": "SCH-MTS-04",
        "name": "Mt. Pleasant High School",
        "province_code": "MTS",
        "district_code": "mts-imk",
        "type": "SECONDARY",
        "address": "Plot 218, Insiza",
        "phone": "+263715428914",
        "email": "info@mtpleasant.edu.zw",
        "founded_year": 1990,
        "principal_name": "Pardon Mudenda",
        "total_students": 80,
        "boys": 41,
        "girls": 39,
        "total_teachers": 25,
        "total_classes": 8,
        "student_teacher_ratio": 3.2,
        "attendance_rate": 91.5,
        "average_mark": 64.0,
        "pass_rate": 86.2,
        "billed_usd": 53200.0,
        "collected_usd": 35839.91,
        "outstanding_usd": 17360.09,
        "collection_rate": 67.4,
        "payments_count": 106
    },
    {
        "id": "e650a5e9-4583-eaf0-1730-a8b179d530ec",
        "code": "SCH-MTS-05",
        "name": "Pumula Primary School",
        "province_code": "MTS",
        "district_code": "mts-mgw",
        "type": "PRIMARY",
        "address": "Plot 443, Mangwe",
        "phone": "+263715641923",
        "email": "info@pumula.edu.zw",
        "founded_year": 1960,
        "principal_name": "Tendai Makoni",
        "total_students": 80,
        "boys": 47,
        "girls": 33,
        "total_teachers": 25,
        "total_classes": 8,
        "student_teacher_ratio": 3.2,
        "attendance_rate": 91.8,
        "average_mark": 63.8,
        "pass_rate": 83.8,
        "billed_usd": 37200.0,
        "collected_usd": 26240.56,
        "outstanding_usd": 10959.44,
        "collection_rate": 70.5,
        "payments_count": 93
    },
    {
        "id": "fa0b6fc5-ca9a-3084-7c7e-437f45b68410",
        "code": "SCH-MTS-06",
        "name": "Chinhoyi High School",
        "province_code": "MTS",
        "district_code": "mts-mtb",
        "type": "SECONDARY",
        "address": "Plot 278, Matobo",
        "phone": "+263713710895",
        "email": "info@chinhoyi.edu.zw",
        "founded_year": 2005,
        "principal_name": "Liberty Chari",
        "total_students": 80,
        "boys": 50,
        "girls": 30,
        "total_teachers": 25,
        "total_classes": 8,
        "student_teacher_ratio": 3.2,
        "attendance_rate": 91.6,
        "average_mark": 63.0,
        "pass_rate": 80.9,
        "billed_usd": 53200.0,
        "collected_usd": 35622.85,
        "outstanding_usd": 17577.15,
        "collection_rate": 67.0,
        "payments_count": 81
    },
    {
        "id": "a1a821f2-5f55-e026-0736-7ec0b00ccf6b",
        "code": "SCH-MID-01",
        "name": "Nkayi High School",
        "province_code": "MID",
        "district_code": "mid-gwr",
        "type": "SECONDARY",
        "address": "Plot 124, Gweru",
        "phone": "+263712262382",
        "email": "info@nkayi.edu.zw",
        "founded_year": 2018,
        "principal_name": "Takudzwa Manyika",
        "total_students": 80,
        "boys": 34,
        "girls": 46,
        "total_teachers": 25,
        "total_classes": 8,
        "student_teacher_ratio": 3.2,
        "attendance_rate": 91.9,
        "average_mark": 63.7,
        "pass_rate": 80.9,
        "billed_usd": 53200.0,
        "collected_usd": 35044.69,
        "outstanding_usd": 18155.31,
        "collection_rate": 65.9,
        "payments_count": 81
    },
    {
        "id": "9db995c6-fcb6-ecf0-3d2f-2c5d9f96a847",
        "code": "SCH-MID-02",
        "name": "Mufakose High School",
        "province_code": "MID",
        "district_code": "mid-czi",
        "type": "SECONDARY",
        "address": "Plot 606, Chirumhanzu",
        "phone": "+263713484601",
        "email": "info@mufakose.edu.zw",
        "founded_year": 1985,
        "principal_name": "Tonderai Sibanda",
        "total_students": 80,
        "boys": 37,
        "girls": 43,
        "total_teachers": 25,
        "total_classes": 8,
        "student_teacher_ratio": 3.2,
        "attendance_rate": 92.0,
        "average_mark": 65.1,
        "pass_rate": 85.0,
        "billed_usd": 53200.0,
        "collected_usd": 37719.08,
        "outstanding_usd": 15480.92,
        "collection_rate": 70.9,
        "payments_count": 83
    },
    {
        "id": "29ea75f9-0808-dfab-58f7-5d59796757e3",
        "code": "SCH-MID-03",
        "name": "Goromonzi Primary School",
        "province_code": "MID",
        "district_code": "mid-gkw",
        "type": "PRIMARY",
        "address": "Plot 965, Gokwe North",
        "phone": "+263711669324",
        "email": "info@goromonzi.edu.zw",
        "founded_year": 2015,
        "principal_name": "Honest Mugabe",
        "total_students": 80,
        "boys": 50,
        "girls": 30,
        "total_teachers": 25,
        "total_classes": 8,
        "student_teacher_ratio": 3.2,
        "attendance_rate": 91.1,
        "average_mark": 64.1,
        "pass_rate": 83.2,
        "billed_usd": 37200.0,
        "collected_usd": 26625.34,
        "outstanding_usd": 10574.66,
        "collection_rate": 71.6,
        "payments_count": 94
    },
    {
        "id": "c2ac4a9b-ff5e-9f1f-5159-4d8863f65f01",
        "code": "SCH-MID-04",
        "name": "Glen View High School",
        "province_code": "MID",
        "district_code": "mid-gks",
        "type": "SECONDARY",
        "address": "Plot 372, Gokwe South",
        "phone": "+263717817881",
        "email": "info@glenview.edu.zw",
        "founded_year": 1997,
        "principal_name": "Takudzwa Chinhoyi",
        "total_students": 80,
        "boys": 47,
        "girls": 33,
        "total_teachers": 25,
        "total_classes": 8,
        "student_teacher_ratio": 3.2,
        "attendance_rate": 91.7,
        "average_mark": 63.3,
        "pass_rate": 81.8,
        "billed_usd": 53200.0,
        "collected_usd": 38544.89,
        "outstanding_usd": 14655.11,
        "collection_rate": 72.5,
        "payments_count": 87
    },
    {
        "id": "115179a6-fa48-38ff-49ad-297d6b4a2c84",
        "code": "SCH-MID-05",
        "name": "Chiredzi High School",
        "province_code": "MID",
        "district_code": "mid-kwk",
        "type": "SECONDARY",
        "address": "Plot 840, Kwekwe",
        "phone": "+263713970445",
        "email": "info@chiredzi.edu.zw",
        "founded_year": 2014,
        "principal_name": "Knowledge Ncube",
        "total_students": 80,
        "boys": 44,
        "girls": 36,
        "total_teachers": 25,
        "total_classes": 8,
        "student_teacher_ratio": 3.2,
        "attendance_rate": 93.0,
        "average_mark": 63.9,
        "pass_rate": 82.3,
        "billed_usd": 53200.0,
        "collected_usd": 37718.97,
        "outstanding_usd": 15481.03,
        "collection_rate": 70.9,
        "payments_count": 88
    },
    {
        "id": "3b9cd96d-a9f9-c0b9-e740-0cdb04706b0e",
        "code": "SCH-MID-06",
        "name": "St. Mary's High School",
        "province_code": "MID",
        "district_code": "mid-mbr",
        "type": "SECONDARY",
        "address": "Plot 350, Mberengwa",
        "phone": "+263717907400",
        "email": "info@stmarys.edu.zw",
        "founded_year": 2009,
        "principal_name": "Daniel Mutema",
        "total_students": 80,
        "boys": 39,
        "girls": 41,
        "total_teachers": 25,
        "total_classes": 8,
        "student_teacher_ratio": 3.2,
        "attendance_rate": 92.3,
        "average_mark": 63.1,
        "pass_rate": 82.6,
        "billed_usd": 53200.0,
        "collected_usd": 35622.64,
        "outstanding_usd": 17577.36,
        "collection_rate": 67.0,
        "payments_count": 79
    }
];

export const MOCK_PROVINCE_BREAKDOWN: MockProvinceBreakdown[] = [
    {
        "province_code": "BYO",
        "province_name": "Bulawayo Metropolitan",
        "region": "Matabeleland",
        "capital": "Bulawayo",
        "schools_count": 6,
        "districts_with_schools": 6,
        "total_students": 480,
        "total_teachers": 150,
        "student_teacher_ratio": 3.2,
        "boys": 244,
        "girls": 236,
        "average_attendance_rate": 92.0,
        "average_pass_rate": 82.3,
        "billed_usd": 287200.0,
        "collected_usd": 193030.63,
        "outstanding_usd": 94169.37,
        "collection_rate": 67.2
    },
    {
        "province_code": "HRE",
        "province_name": "Harare Metropolitan",
        "region": "Mashonaland",
        "capital": "Harare",
        "schools_count": 6,
        "districts_with_schools": 6,
        "total_students": 480,
        "total_teachers": 150,
        "student_teacher_ratio": 3.2,
        "boys": 254,
        "girls": 226,
        "average_attendance_rate": 92.6,
        "average_pass_rate": 82.3,
        "billed_usd": 287200.0,
        "collected_usd": 204354.94,
        "outstanding_usd": 82845.06,
        "collection_rate": 71.2
    },
    {
        "province_code": "MAN",
        "province_name": "Manicaland",
        "region": "Eastern Highlands",
        "capital": "Mutare",
        "schools_count": 6,
        "districts_with_schools": 6,
        "total_students": 480,
        "total_teachers": 150,
        "student_teacher_ratio": 3.2,
        "boys": 245,
        "girls": 235,
        "average_attendance_rate": 91.7,
        "average_pass_rate": 84.7,
        "billed_usd": 255200.0,
        "collected_usd": 178852.36,
        "outstanding_usd": 76347.64,
        "collection_rate": 70.1
    },
    {
        "province_code": "MCE",
        "province_name": "Mashonaland Central",
        "region": "Mashonaland",
        "capital": "Bindura",
        "schools_count": 6,
        "districts_with_schools": 6,
        "total_students": 480,
        "total_teachers": 150,
        "student_teacher_ratio": 3.2,
        "boys": 244,
        "girls": 236,
        "average_attendance_rate": 92.0,
        "average_pass_rate": 83.2,
        "billed_usd": 271200.0,
        "collected_usd": 190818.99,
        "outstanding_usd": 80381.01,
        "collection_rate": 70.4
    },
    {
        "province_code": "MEA",
        "province_name": "Mashonaland East",
        "region": "Mashonaland",
        "capital": "Marondera",
        "schools_count": 6,
        "districts_with_schools": 6,
        "total_students": 480,
        "total_teachers": 150,
        "student_teacher_ratio": 3.2,
        "boys": 241,
        "girls": 239,
        "average_attendance_rate": 92.2,
        "average_pass_rate": 82.3,
        "billed_usd": 271200.0,
        "collected_usd": 189657.94,
        "outstanding_usd": 81542.06,
        "collection_rate": 69.9
    },
    {
        "province_code": "MWE",
        "province_name": "Mashonaland West",
        "region": "Mashonaland",
        "capital": "Chinhoyi",
        "schools_count": 6,
        "districts_with_schools": 6,
        "total_students": 480,
        "total_teachers": 150,
        "student_teacher_ratio": 3.2,
        "boys": 227,
        "girls": 253,
        "average_attendance_rate": 92.2,
        "average_pass_rate": 81.8,
        "billed_usd": 239200.0,
        "collected_usd": 166513.22,
        "outstanding_usd": 72686.78,
        "collection_rate": 69.6
    },
    {
        "province_code": "MAS",
        "province_name": "Masvingo",
        "region": "Southern",
        "capital": "Masvingo",
        "schools_count": 6,
        "districts_with_schools": 6,
        "total_students": 480,
        "total_teachers": 150,
        "student_teacher_ratio": 3.2,
        "boys": 256,
        "girls": 224,
        "average_attendance_rate": 92.2,
        "average_pass_rate": 82.4,
        "billed_usd": 255200.0,
        "collected_usd": 177655.77,
        "outstanding_usd": 77544.23,
        "collection_rate": 69.6
    },
    {
        "province_code": "MTN",
        "province_name": "Matabeleland North",
        "region": "Matabeleland",
        "capital": "Lupane",
        "schools_count": 6,
        "districts_with_schools": 6,
        "total_students": 480,
        "total_teachers": 150,
        "student_teacher_ratio": 3.2,
        "boys": 235,
        "girls": 245,
        "average_attendance_rate": 91.9,
        "average_pass_rate": 83.6,
        "billed_usd": 287200.0,
        "collected_usd": 204364.92,
        "outstanding_usd": 82835.08,
        "collection_rate": 71.2
    },
    {
        "province_code": "MTS",
        "province_name": "Matabeleland South",
        "region": "Matabeleland",
        "capital": "Gwanda",
        "schools_count": 6,
        "districts_with_schools": 6,
        "total_students": 480,
        "total_teachers": 150,
        "student_teacher_ratio": 3.2,
        "boys": 257,
        "girls": 223,
        "average_attendance_rate": 92.0,
        "average_pass_rate": 84.0,
        "billed_usd": 287200.0,
        "collected_usd": 195050.24,
        "outstanding_usd": 92149.76,
        "collection_rate": 67.9
    },
    {
        "province_code": "MID",
        "province_name": "Midlands",
        "region": "Central",
        "capital": "Gweru",
        "schools_count": 6,
        "districts_with_schools": 6,
        "total_students": 480,
        "total_teachers": 150,
        "student_teacher_ratio": 3.2,
        "boys": 251,
        "girls": 229,
        "average_attendance_rate": 92.0,
        "average_pass_rate": 82.6,
        "billed_usd": 303200.0,
        "collected_usd": 211275.61,
        "outstanding_usd": 91924.39,
        "collection_rate": 69.7
    }
];

export const MOCK_NATIONAL_KPIS: MockNationalKpis = {
    "total_provinces": 10,
    "total_districts": 74,
    "total_schools": 60,
    "total_students": 4800,
    "total_boys": 2454,
    "total_girls": 2346,
    "total_teachers": 1500,
    "total_classes": 480,
    "average_attendance_rate": 92.1,
    "average_pass_rate": 82.9,
    "billed_usd": 2744000.0,
    "collected_usd": 1911574.62,
    "outstanding_usd": 832425.38,
    "collection_rate": 69.7
};

export const MOCK_TOP_SCHOOLS: MockTopSchool[] = [
    {
        "id": "ca01ee94-d011-24e6-0bcc-e976a1c807e2",
        "name": "Murewa Primary School",
        "code": "SCH-MAN-02",
        "province_code": "MAN",
        "district_code": "man-mtr",
        "pass_rate": 89.6,
        "average_mark": 67.4,
        "attendance_rate": 91.7,
        "total_students": 80
    },
    {
        "id": "732563dc-be62-8524-d52f-93d23b2d3336",
        "name": "Kariba High School",
        "code": "SCH-MAN-03",
        "province_code": "MAN",
        "district_code": "man-bua",
        "pass_rate": 88.0,
        "average_mark": 66.0,
        "attendance_rate": 92.2,
        "total_students": 80
    },
    {
        "id": "41fefce5-116b-9c12-f6f0-124b98ce8296",
        "name": "Founders High School",
        "code": "SCH-HRE-04",
        "province_code": "HRE",
        "district_code": "hre-mb",
        "pass_rate": 87.7,
        "average_mark": 65.6,
        "attendance_rate": 92.3,
        "total_students": 80
    },
    {
        "id": "9f7ebf3a-ed3e-0de9-ad70-31132f81db09",
        "name": "Chivhu Primary School",
        "code": "SCH-BYO-03",
        "province_code": "BYO",
        "district_code": "byo-nk",
        "pass_rate": 87.5,
        "average_mark": 66.5,
        "attendance_rate": 92.0,
        "total_students": 80
    },
    {
        "id": "4e28586e-4c8f-768c-4007-fde194d2a8ab",
        "name": "Vision High School",
        "code": "SCH-MTN-06",
        "province_code": "MTN",
        "district_code": "mtn-tsh",
        "pass_rate": 87.4,
        "average_mark": 65.9,
        "attendance_rate": 92.0,
        "total_students": 80
    },
    {
        "id": "2523e570-59a4-1199-7797-04bdd56b999e",
        "name": "Nkayi Primary School",
        "code": "SCH-MEA-01",
        "province_code": "MEA",
        "district_code": "mea-mrn",
        "pass_rate": 87.1,
        "average_mark": 64.1,
        "attendance_rate": 91.7,
        "total_students": 80
    },
    {
        "id": "b06c3067-77d2-c78d-a693-979249f18514",
        "name": "Mt. Pleasant High School",
        "code": "SCH-MTS-04",
        "province_code": "MTS",
        "district_code": "mts-imk",
        "pass_rate": 86.2,
        "average_mark": 64.0,
        "attendance_rate": 91.5,
        "total_students": 80
    },
    {
        "id": "9aed300f-ecf7-8178-3674-26c9f9c19b17",
        "name": "Gwanda High School",
        "code": "SCH-MTS-03",
        "province_code": "MTS",
        "district_code": "mts-bmb",
        "pass_rate": 86.0,
        "average_mark": 65.5,
        "attendance_rate": 92.9,
        "total_students": 80
    },
    {
        "id": "1d1e8ed1-5d89-1f1c-4a2a-e972980e260b",
        "name": "Kariba Primary School",
        "code": "SCH-MTN-03",
        "province_code": "MTN",
        "district_code": "mtn-bbg",
        "pass_rate": 86.0,
        "average_mark": 65.2,
        "attendance_rate": 92.7,
        "total_students": 80
    },
    {
        "id": "9ea0ced9-a201-c174-db78-df84d26ece83",
        "name": "Hwange High School",
        "code": "SCH-HRE-05",
        "province_code": "HRE",
        "district_code": "hre-gw",
        "pass_rate": 85.7,
        "average_mark": 64.8,
        "attendance_rate": 92.7,
        "total_students": 80
    }
];

export function getProvinceByCode(code: string): MockProvince | undefined {
    return MOCK_PROVINCES.find((p) => p.code === code);
}

export function getProvinceBreakdown(code: string): MockProvinceBreakdown | undefined {
    return MOCK_PROVINCE_BREAKDOWN.find((p) => p.province_code === code);
}

export function getDistrictsByProvince(code: string): MockDistrict[] {
    return MOCK_DISTRICTS.filter((d) => d.province_code === code);
}

export function getSchoolsByProvince(code: string): MockSchoolNational[] {
    return MOCK_SCHOOLS_NATIONAL.filter((s) => s.province_code === code);
}

export function getSchoolsByDistrict(code: string): MockSchoolNational[] {
    return MOCK_SCHOOLS_NATIONAL.filter((s) => s.district_code === code);
}

export function getSchoolById(id: string): MockSchoolNational | undefined {
    return MOCK_SCHOOLS_NATIONAL.find((s) => s.id === id);
}
